version: '3.8'

services:
  django:
    environment:
      - DEBUG=False
      - DATABASE_URL=postgres://habit_user:habit_password@postgres:5432/habit_tracker
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=your-domain.com,84.252.141.200

  nginx:
    ports:
      - "80:80"
      - "443:443"  # если будет SSL

volumes:
  postgres_data:
  static_volume:
  media_volume:
